version: '3.7'
services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    environment:
      NODE_ENV: Production
      PORT: 8000
      DB_HOST: mysql
      DB_USER: root
      DB_PWD: password
      DB_PORT: 3306
      DB_NAME: notepad_web_app
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    ports:
      - "8000:8000"
    restart: unless-stopped

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8081:8080
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - redis_volume:/data

volumes:
  mysql_volume:
  redis_volume:
    driver: local
