version: '3.7'
services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: Production
      PORT: 8000
      DB_HOST: mysql
      DB_USER: root
      DB_PWD: password
      DB_PORT: 3306
      DB_NAME: notepad_web_app
    ports:
      - "8000:8000"
    restart: unless-stopped

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8081:8080
    restart: unless-stopped

volumes:
  mysql_volume:
